spring.application.name=GoldenNews

spring.datasource.url=jdbc:postgresql://postgres:5432/${DATABASE_DB}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# real risky(data loss) for prod
# cuz it auto updates changes in entitys
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
